/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LuisRamirez
 */
public class employee extends javax.swing.JFrame {

    /**
     * Creates new form employee
     */
    public employee() {
        initComponents();
        Connect();
        load();
    }
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    PreparedStatement pst2;
    PreparedStatement pst3;
    DefaultTableModel df;
    ResultSet rs;
    ResultSet rs1;
    ResultSet rs2;
    
    public void load() {
        int a;
        try {
            pst = con.prepareStatement("select * from EMPLOYEE, JOB, DEPARTMENT where EMPLOYEE.ID = JOB.EMPLOYEE_ID AND DEPARTMENT.EMPLOYEE_ID = EMPLOYEE.ID");
            
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
           
            a = rd.getColumnCount();
            df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
               Vector v2 = new Vector();
               for(int i=1; i<=a; i++)
               {
                   v2.add(rs.getString("ID"));
                   v2.add(rs.getString("FNAME"));
                   v2.add(rs.getString("LNAME"));
                   v2.add(rs.getString("DOB"));
                   v2.add(rs.getString("PHONE"));
                   v2.add(rs.getString("EMAIL"));
                   v2.add(rs.getString("HIREDATE"));
                   v2.add(rs.getString("STATE"));
                   v2.add(rs.getString("CITY"));
                   v2.add(rs.getString("ZIP"));
                   v2.add(rs.getString("ADDRESS"));
                   v2.add(rs.getString("TITLE"));
                   v2.add(rs.getString("PERMISSION_LEVEL"));
                   v2.add(rs.getString("NAME"));
                   
               }
               df.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Connect()
    {
      
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/IT_Management?allowPublicKeyRetrieval=true&useSSL=false", "root", "Bornready16");
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
        }
   
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtempfirst = new javax.swing.JTextField();
        txtemplast = new javax.swing.JTextField();
        txtempdob = new javax.swing.JTextField();
        txtempphone = new javax.swing.JTextField();
        txtempemail = new javax.swing.JTextField();
        txtemphire = new javax.swing.JTextField();
        txtempstate = new javax.swing.JTextField();
        txtempcity = new javax.swing.JTextField();
        txtempaddress = new javax.swing.JTextField();
        txtempzip = new javax.swing.JTextField();
        txtempjob = new javax.swing.JTextField();
        txtempdepart = new javax.swing.JTextField();
        txtempper = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtempsearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1160, 720));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Employee");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Basic Information");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Date of Birth:");

        jLabel6.setText("Phone #:");

        jLabel7.setText("Email Address:");

        jLabel8.setText("Date of Hire:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("Work Information");

        jLabel10.setText("Job Title:");

        jLabel11.setText("Department:");

        jLabel12.setText("Permissions Level:");

        jLabel16.setText("State:");

        jLabel17.setText("City:");

        jLabel18.setText("Street Address:");

        jLabel19.setText("Zip Code:");

        txtempfirst.setPreferredSize(new java.awt.Dimension(84, 24));

        txtemplast.setPreferredSize(new java.awt.Dimension(84, 24));

        txtempdob.setPreferredSize(new java.awt.Dimension(84, 24));

        txtempphone.setPreferredSize(new java.awt.Dimension(84, 24));

        txtempemail.setPreferredSize(new java.awt.Dimension(84, 24));

        txtemphire.setPreferredSize(new java.awt.Dimension(84, 24));
        txtemphire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemphireActionPerformed(evt);
            }
        });

        txtempstate.setPreferredSize(new java.awt.Dimension(84, 24));

        txtempcity.setPreferredSize(new java.awt.Dimension(84, 24));

        txtempaddress.setPreferredSize(new java.awt.Dimension(84, 24));

        txtempzip.setPreferredSize(new java.awt.Dimension(84, 24));

        txtempjob.setPreferredSize(new java.awt.Dimension(84, 24));

        txtempdepart.setPreferredSize(new java.awt.Dimension(84, 24));

        txtempper.setPreferredSize(new java.awt.Dimension(84, 24));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(81, 81, 81))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtempzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtempaddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtempcity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtempstate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtempdob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtempphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtempemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtemphire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtemplast, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtempfirst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtempjob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtempdepart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtempper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtempfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtempjob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(txtemplast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtempdepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(txtempdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtempper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtempphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtempemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtemphire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtempstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtempcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtempzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtempaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First ", "Last ", "DOB", "Phone #", "Email", "DOH", "State", "City", "Zip", "Address", "Job", "Permissions", "Department"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel20.setText("Search:");

        txtempsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtempsearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(txtempsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtempsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(62, 62, 62)
                                .addComponent(jButton2)
                                .addGap(47, 47, 47)
                                .addComponent(jButton3)
                                .addGap(52, 52, 52)
                                .addComponent(jButton4)
                                .addGap(122, 122, 122)
                                .addComponent(jButton5)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        df = (DefaultTableModel)jTable1.getModel();
        int selected = jTable1.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());

            String efirst = txtempfirst.getText();
            String elast = txtemplast.getText();
            String edob = txtempdob.getText();
            String ephone = txtempphone.getText();
            String eemail = txtempemail.getText();
            String ehire = txtemphire.getText();
            String estate = txtempstate.getText();
            String ecity = txtempcity.getText();
            String ezip = txtempzip.getText();
            String eaddress = txtempaddress.getText();
            String ejob = txtempjob.getText();
            String edepart = txtempdepart.getText();
            String eper = txtempper.getText();
            int employid = 0;
            int jobid = 0;
            int departid = 0;
            
        // TODO add your handling code here:
        try {
            String query1 = "update EMPLOYEE set FNAME = ?, LNAME = ?, DOB = ?, PHONE = ?, EMAIL = ?, HIREDATE = ?, STATE = ?, CITY = ?, ZIP = ?, ADDRESS = ? where id = ?";
            
            pst = con.prepareStatement(query1, Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, efirst);
            pst.setString(2, elast);
            pst.setString(3, edob);
            pst.setString(4, ephone);
            pst.setString(5, eemail);
            pst.setString(6, ehire);
            pst.setString(7, estate);
            pst.setString(8, ecity);
            pst.setString(9, ezip);
            pst.setString(10, eaddress);
            pst.setInt(11, id);
            pst.executeUpdate();
            rs = pst.getGeneratedKeys();
            
            if(rs.next()){
                
                employid = rs.getInt(1);
            }
            
            String query2 = "update JOB set TITLE = ?, PERMISSION_LEVEL = ? where ID = ?";
            pst1 = con.prepareStatement(query2, Statement.RETURN_GENERATED_KEYS);
            pst1.setString(1, ejob);
            pst1.setString(2, eper);
            
            pst1.setInt(3, id);
            pst1.executeUpdate();
            rs = pst1.getGeneratedKeys();
            
            String query3 = "update DEPARTMENT set NAME = ? WHERE ID = ?";
            pst2 = con.prepareStatement(query3, Statement.RETURN_GENERATED_KEYS);
            pst2.setString(1, edepart);
            
            pst2.setInt(2, id);
            pst2.executeUpdate();
            rs = pst1.getGeneratedKeys();
          
            JOptionPane.showMessageDialog(this, "Employee Updated Successfully");

            txtempfirst.setText("");
            txtemplast.setText("");
            txtempdob.setText("");
            txtempphone.setText("");
            txtempemail.setText("");
            txtemphire.setText("");
            txtempstate.setText("");
            txtempcity.setText("");
            txtempzip.setText("");
            txtempaddress.setText("");
            txtempjob.setText("");
            txtempdepart.setText("");
            txtempper.setText("");
            txtempfirst.requestFocus();
            load();
            jButton1.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtemphireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemphireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemphireActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            String efirst = txtempfirst.getText();
            String elast = txtemplast.getText();
            String edob = txtempdob.getText();
            String ephone = txtempphone.getText();
            String eemail = txtempemail.getText();
            String ehire = txtemphire.getText();
            String estate = txtempstate.getText();
            String ecity = txtempcity.getText();
            String ezip = txtempzip.getText();
            String eaddress = txtempaddress.getText();
            
            String ejob = txtempjob.getText();
            String eper = txtempper.getText();
            String edepart = txtempdepart.getText();
            
            int employid = 0;
            int jobid = 0;
            int departid = 0;
           
            // TODO add your handling code here:
            String query1 = "insert into EMPLOYEE(FNAME, LNAME, DOB, PHONE, EMAIL, HIREDATE, STATE, CITY, ZIP, ADDRESS)VALUES(?,?,?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(query1, Statement.RETURN_GENERATED_KEYS);
            
            pst.setString(1, efirst);
            pst.setString(2, elast);
            pst.setString(3, edob);
            pst.setString(4, ephone);
            pst.setString(5, eemail);
            pst.setString(6, ehire);
            pst.setString(7, estate);
            pst.setString(8, ecity);
            pst.setString(9, ezip);
            pst.setString(10, eaddress);
            pst.executeUpdate();
            rs = pst.getGeneratedKeys();
            
            if(rs.next()){
                
                employid = rs.getInt(1);
            }
            
            String query2 = "insert into JOB(TITLE, PERMISSION_LEVEL, EMPLOYEE_ID)values(?,?,?)";
            pst1 = con.prepareStatement(query2, Statement.RETURN_GENERATED_KEYS);
            
            pst1.setString(1, ejob);
            pst1.setString(2, eper);
            pst1.setInt(3, employid);
            pst1.executeUpdate();
            rs = pst1.getGeneratedKeys();
            
            if(rs.next()){
                
                jobid = rs.getInt(1);
            }
            
            String query3 = "insert into DEPARTMENT(NAME, EMPLOYEE_ID)VALUES(?,?)";
            pst2 = con.prepareStatement(query3, Statement.RETURN_GENERATED_KEYS);
            
            pst2.setString(1, edepart);
            pst2.setInt(2, employid);
            pst2.executeUpdate();
            rs = pst2.getGeneratedKeys();

            JOptionPane.showMessageDialog(this, "Employee Added Successfully");
            
            txtempfirst.setText("");
            txtemplast.setText("");
            txtempdob.setText("");
            txtempphone.setText("");
            txtempemail.setText("");
            txtemphire.setText("");
            txtempstate.setText("");
            txtempcity.setText("");
            txtempzip.setText("");
            txtempaddress.setText("");
            txtempjob.setText("");
            txtempdepart.setText("");
            txtempper.setText("");
            txtempfirst.requestFocus();
            load();
        
        } catch (SQLException ex) {
            Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
            txtempfirst.setText("");
            txtemplast.setText("");
            txtempdob.setText("");
            txtempphone.setText("");
            txtempemail.setText("");
            txtemphire.setText("");
            txtempstate.setText("");
            txtempcity.setText("");
            txtempzip.setText("");
            txtempaddress.setText("");
            txtempjob.setText("");
            txtempdepart.setText("");
            txtempper.setText("");
            txtempfirst.requestFocus();
            load();
            jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        df = (DefaultTableModel)jTable1.getModel();
        int selected = jTable1.getSelectedRow();
        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
        
        try {
            // TODO add your handling code here:
                 
            pst = con.prepareStatement("delete from EMPLOYEE where id = ?");
            pst.setInt(1, id);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Employee Deleted Successfully");
            
            txtempfirst.setText("");
            txtemplast.setText("");
            txtempdob.setText("");
            txtempphone.setText("");
            txtempemail.setText("");
            txtemphire.setText("");
            txtempstate.setText("");
            txtempcity.setText("");
            txtempzip.setText("");
            txtempaddress.setText("");
            txtempjob.setText("");
            txtempdepart.setText("");
            txtempper.setText("");
            load();
            jButton1.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         df = (DefaultTableModel)jTable1.getModel();
        int selected = jTable1.getSelectedRow();
        
        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
        txtempfirst.setText(df.getValueAt(selected, 1).toString());
        txtemplast.setText(df.getValueAt(selected, 2).toString());
        txtempdob.setText(df.getValueAt(selected, 3).toString());
        txtempphone.setText(df.getValueAt(selected, 4).toString());
        txtempemail.setText(df.getValueAt(selected, 5).toString());
        txtemphire.setText(df.getValueAt(selected, 6).toString());
        txtempstate.setText(df.getValueAt(selected, 7).toString());
        txtempcity.setText(df.getValueAt(selected, 8).toString());
        txtempzip.setText(df.getValueAt(selected, 9).toString());
        txtempaddress.setText(df.getValueAt(selected, 10).toString());
        txtempjob.setText(df.getValueAt(selected, 11).toString());
        txtempper.setText(df.getValueAt(selected, 12).toString());
        txtempdepart.setText(df.getValueAt(selected, 13).toString());
        
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtempsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtempsearchKeyReleased
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            String sql ="select * from EMPLOYEE, JOB, DEPARTMENT where FNAME = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, txtempsearch.getText());
            
            rs = pst.executeQuery();
            if(rs.next()) {
                String add1 = rs.getString("FNAME");
                txtempfirst.setText(add1);
                String add2 = rs.getString("LNAME");
                txtemplast.setText(add2);
                String add3 = rs.getString("DOB");
                txtempdob.setText(add3);
                String add4 = rs.getString("PHONE");
                txtempphone.setText(add4);
                String add5 = rs.getString("EMAIL");
                txtempemail.setText(add5);
                String add6 = rs.getString("HIREDATE");
                txtemphire.setText(add6);
                String add7 = rs.getString("STATE");
                txtempstate.setText(add7);
                String add8 = rs.getString("CITY");
                txtempcity.setText(add8);
                String add9 = rs.getString("ZIP");
                txtempzip.setText(add9);
                String add10 = rs.getString("ADDRESS");
                txtempaddress.setText(add10);
                String add11 = rs.getString("TITLE");
                txtempjob.setText(add11);
                String add12 = rs.getString("PERMISSION_LEVEL");
                txtempper.setText(add12);
                String add13 = rs.getString("NAME");
                txtempdepart.setText(add13);
            }
        } catch (SQLException ex) {
            Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_txtempsearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtempaddress;
    private javax.swing.JTextField txtempcity;
    private javax.swing.JTextField txtempdepart;
    private javax.swing.JTextField txtempdob;
    private javax.swing.JTextField txtempemail;
    private javax.swing.JTextField txtempfirst;
    private javax.swing.JTextField txtemphire;
    private javax.swing.JTextField txtempjob;
    private javax.swing.JTextField txtemplast;
    private javax.swing.JTextField txtempper;
    private javax.swing.JTextField txtempphone;
    private javax.swing.JTextField txtempsearch;
    private javax.swing.JTextField txtempstate;
    private javax.swing.JTextField txtempzip;
    // End of variables declaration//GEN-END:variables
}
