/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LuisRamirez
 */
public class hardware extends javax.swing.JFrame {

    /**
     * Creates new form hardware
     */
    public hardware() {
        initComponents();
        Connect();
        load();
    }
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    PreparedStatement pst2;
    DefaultTableModel df;
    ResultSet rs;
    
    public void load() {
        int a;
        try {
            pst = con.prepareStatement("select * from HARDWARE, WARRANTY where HARDWARE.ID = WARRANTY.HARDWARE_ID");
            
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
           
            a = rd.getColumnCount();
            df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
               Vector v2 = new Vector();
               for(int i=1; i<=a; i++)
               {
                   v2.add(rs.getString("ID"));
                   v2.add(rs.getString("SN"));
                   v2.add(rs.getString("MODEL"));
                   v2.add(rs.getString("RAM"));
                   v2.add(rs.getString("OS"));
                   v2.add(rs.getString("COST"));
                   v2.add(rs.getString("TYPE"));
                   v2.add(rs.getString("EMPLOYEE_ID"));
                   v2.add(rs.getString("EXPIRDATE"));
                   v2.add(rs.getString("STARTDATE"));
                   v2.add(rs.getString("VENDOR_ID"));
                  
               }
               df.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(hardware.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/IT_Management?allowPublicKeyRetrieval=true&useSSL=false", "root", "Bornready16");
                   
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(hardware.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(hardware.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txthsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txthmodel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txthserial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txthos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txthram = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txthcost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txthtype = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txthwarrstart = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txthwarrend = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtempid = new javax.swing.JTextField();
        txtvendid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Search:");

        txthsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthsearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txthsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txthsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Hardware");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Hardware Serial:");

        jLabel4.setText("Hardware Model:");

        jLabel5.setText("Hardware RAM:");

        jLabel6.setText("Hardware OS:");

        jLabel7.setText("Hardware Cost:");

        jLabel8.setText("Hardware Type:");

        jLabel9.setText("Warranty Start:");

        jLabel10.setText("Warranty Expir.:");

        jLabel11.setText("Employee ID");

        jLabel12.setText("Vendor ID");

        txtempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(txthmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txthserial, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txthram, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtempid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addComponent(txthos, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txthcost, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthtype, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthwarrstart, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtvendid, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txthwarrend, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthserial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthwarrstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthwarrend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvendid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HW ID", "HW Serial", "HW Model", "HW RAM", "HW OS", "HW Cost", "HW Type", "Employee ID", "HW End", "HW Start", "Vendor ID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(50, 50, 50)
                                .addComponent(jButton2)
                                .addGap(47, 47, 47)
                                .addComponent(jButton3)
                                .addGap(44, 44, 44)
                                .addComponent(jButton4)
                                .addGap(95, 95, 95)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel1)))
                        .addGap(0, 451, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempidActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            txthserial.setText("");
            txthmodel.setText("");
            txthram.setText("");
            txthos.setText("");
            txtempid.setText("");
            txthcost.setText("");
            txthtype.setText("");
            txthwarrend.setText("");
            txthwarrstart.setText("");
            txtvendid.setText("");
            txthserial.requestFocus();
            load();
            jButton1.setEnabled(true);
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            String hserial = txthserial.getText();
            String hmodel = txthmodel.getText();
            String hram = txthram.getText();
            String hos = txthos.getText();
            String empid = txtempid.getText();
            String hcost = txthcost.getText();
            String htype = txthtype.getText();
            String hwarrend = txthwarrend.getText();
            String hwarrstart = txthwarrstart.getText();
            String vendid = txtvendid.getText();
            int warrid = 0;
            
            String query1 = "insert into HARDWARE(SN, MODEL, RAM, OS, COST, TYPE, EMPLOYEE_ID, VENDOR_ID)VALUES(?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(query1, Statement.RETURN_GENERATED_KEYS);
            
            pst.setString(1, hserial);
            pst.setString(2, hmodel);
            pst.setString(3, hram);
            pst.setString(4, hos);
            pst.setString(5, hcost);
            pst.setString(6, htype);
            pst.setString(7, empid );
            pst.setString(8, vendid);
            pst.executeUpdate();
            rs = pst.getGeneratedKeys();
            
            if(rs.next()){
                
                warrid = rs.getInt(1);
            }
            
            String query2 = "insert into WARRANTY(EXPIRDATE, STARTDATE, HARDWARE_ID)VALUES(?,?,?)";
            pst1 = con.prepareStatement(query2, Statement.RETURN_GENERATED_KEYS);
            pst1.setString(1, hwarrend);
            pst1.setString(2, hwarrstart);
            pst1.setInt(3, warrid);
            pst1.executeUpdate();
            rs = pst1.getGeneratedKeys();
            
            if(rs.next()){
                
                warrid = rs.getInt(1);
            }
            
            JOptionPane.showMessageDialog(this, "Hardware Added Successfully");
            
            txthserial.setText("");
            txthmodel.setText("");
            txthram.setText("");
            txthos.setText("");
            txtempid.setText("");
            txthcost.setText("");
            txthtype.setText("");
            txthwarrend.setText("");
            txthwarrstart.setText("");
            txtvendid.setText("");
            txthserial.requestFocus();
            load();
            
        } catch (SQLException ex) {
            Logger.getLogger(hardware.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        df = (DefaultTableModel)jTable1.getModel();
        int selected = jTable1.getSelectedRow();
        
        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
        txthserial.setText(df.getValueAt(selected, 1).toString());
        txthmodel.setText(df.getValueAt(selected, 2).toString());
        txthram.setText(df.getValueAt(selected, 3).toString());
        txthos.setText(df.getValueAt(selected, 4).toString());
        txthcost.setText(df.getValueAt(selected, 5).toString());
        txthtype.setText(df.getValueAt(selected, 6).toString());
        txtempid.setText(df.getValueAt(selected, 7).toString());
        txthwarrend.setText(df.getValueAt(selected, 8).toString());
        txthwarrstart.setText(df.getValueAt(selected, 9).toString());
        txtvendid.setText(df.getValueAt(selected, 10).toString());
      
        jButton1.setEnabled(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        df = (DefaultTableModel)jTable1.getModel();
        int selected = jTable1.getSelectedRow();

        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());

            String hserial = txthserial.getText();
            String hmodel = txthmodel.getText();
            String hram = txthram.getText();
            String hos = txthos.getText();
            String empid = txtempid.getText();
            String hcost = txthcost.getText();
            String htype = txthtype.getText();
            String hwarrend = txthwarrend.getText();
            String hwarrstart = txthwarrstart.getText();
            String vendid = txtvendid.getText();
            int warrid = 0;
            
        // TODO add your handling code here:
        
        String query2 = "update HARDWARE set SN = ?, MODEL = ?, RAM = ?, OS = ?, COST = ?, TYPE = ?, EMPLOYEE_ID = ?, VENDOR_ID = ? where ID = ?";
         try{   
            pst = con.prepareStatement(query2, Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, hserial);
            pst.setString(2, hmodel);
            pst.setString(3, hram);
            pst.setString(4, hos);
            pst.setString(5, hcost);
            pst.setString(6, htype);
            pst.setString(7, empid );
            pst.setString(8, vendid);
            pst.setInt(9, id);
            pst.executeUpdate();
            rs = pst.getGeneratedKeys();
            
            if(rs.next()){
                
                warrid = rs.getInt(1);
            }
        
            String query1 = "update WARRANTY set EXPIRDATE = ?, STARTDATE = ? where id =?";
            pst1 = con.prepareStatement(query1, Statement.RETURN_GENERATED_KEYS);
            pst1.setString(1, hwarrend);
            pst1.setString(2, hwarrstart);
            
            pst1.setInt(3, id);
            pst1.executeUpdate();
            rs = pst1.getGeneratedKeys();
           
            JOptionPane.showMessageDialog(this, "Software Updated Successfully");

            txthserial.setText("");
            txthmodel.setText("");
            txthram.setText("");
            txthos.setText("");
            txtempid.setText("");
            txthcost.setText("");
            txthtype.setText("");
            txthwarrend.setText("");
            txthwarrstart.setText("");
            txtvendid.setText("");
            txthserial.requestFocus();
            load();
            jButton1.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(hardware.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        df = (DefaultTableModel)jTable1.getModel();
        int selected = jTable1.getSelectedRow();
        int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
        
        try {
            // TODO add your handling code here:
                 
            pst = con.prepareStatement("delete from HARDWARE where ID = ?");
            pst.setInt(1, id);
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Hardware Deleted Successfully");
            
            txthserial.setText("");
            txthmodel.setText("");
            txthram.setText("");
            txthos.setText("");
            txtempid.setText("");
            txthcost.setText("");
            txthtype.setText("");
            txthwarrend.setText("");
            txthwarrstart.setText("");
            txtvendid.setText("");
            txthserial.requestFocus();
            load();
            jButton1.setEnabled(true);
            
            } catch (SQLException ex) {
            Logger.getLogger(hardware.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txthsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthsearchKeyReleased
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            String sql ="select * from HARDWARE, WARRANTY where HARDWARE.MODEL = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, txthsearch.getText());
            
            rs = pst.executeQuery();
            if(rs.next()) {
                String add1 = rs.getString("SN");
                txthserial.setText(add1);
                String add2 = rs.getString("MODEL");
                txthmodel.setText(add2);
                String add3 = rs.getString("RAM");
                txthram.setText(add3);
                String add4 = rs.getString("OS");
                txthos.setText(add4);
                String add5 = rs.getString("EMPLOYEE_ID");
                txtempid.setText(add5);
                String add6 = rs.getString("COST");
                txthcost.setText(add6);
                String add7 = rs.getString("TYPE");
                txthtype.setText(add7);
                String add8 = rs.getString("EXPIRDATE");
                txthwarrend.setText(add8);
                String add9 = rs.getString("STARTDATE");
                txthwarrstart.setText(add9);
                String add10 = rs.getString("VENDOR_ID");
                txtvendid.setText(add10);
                
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(hardware.class.getName()).log(Level.SEVERE, null, ex);
        }  
      
    }//GEN-LAST:event_txthsearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hardware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txthcost;
    private javax.swing.JTextField txthmodel;
    private javax.swing.JTextField txthos;
    private javax.swing.JTextField txthram;
    private javax.swing.JTextField txthsearch;
    private javax.swing.JTextField txthserial;
    private javax.swing.JTextField txthtype;
    private javax.swing.JTextField txthwarrend;
    private javax.swing.JTextField txthwarrstart;
    private javax.swing.JTextField txtvendid;
    // End of variables declaration//GEN-END:variables
}
